// <auto-generated />
using System;
using HotelProject.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelProject.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240227042426_HotelApi")]
    partial class HotelApi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelProject.Domain.Entities.Hotel.Aluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlugadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuartosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuartosId");

                    b.ToTable("Aluguel", "Hotel");
                });

            modelBuilder.Entity("HotelProject.Domain.Entities.Hotel.Quartos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Alugado")
                        .HasColumnType("bit");

                    b.Property<int>("Andar")
                        .HasColumnType("int");

                    b.Property<bool>("Manutencao")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quartos", "Hotel");
                });

            modelBuilder.Entity("HotelProject.Domain.Entities.Hotel.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", "Hotel");
                });

            modelBuilder.Entity("HotelProject.Domain.Entities.Hotel.Aluguel", b =>
                {
                    b.HasOne("HotelProject.Domain.Entities.Hotel.Quartos", null)
                        .WithMany("Aluguel")
                        .HasForeignKey("QuartosId");
                });

            modelBuilder.Entity("HotelProject.Domain.Entities.Hotel.Quartos", b =>
                {
                    b.Navigation("Aluguel");
                });
#pragma warning restore 612, 618
        }
    }
}
